export default Object.freeze({
  HOME: "Home",
  BOOK_SUMMARY: "BookSummary",
  BOOK_DETAIL: "BookDetail",
  VIEW_OFFER: "ViewOffer",
  FEATURE_AND_DETAIL: "FeatureAndDetail",
  LISTING_EDIT: "ListingsEdit",
  LOGIN: "Login",
  FORGOT_PASS: "ForgotPass",
  LISTING: "Listing",
  SCAN: "Scan",
  SEARCH: "Search",
  SEARCH_RESULT: "SearchResult",
  MY_PROFILE: "MyProfileScreen",
  MY_PLAN_CREDIT_SCREEN: "MyPlanAndCreditScreen",
  MY_LISTINGS: "MyListings",
  MY_MESSAGES: "MyMessages",
  DELETE_MY_ACCOUNT: "DeleteMyAccountScreen",
  REGISTER: "Register",
  PAYSCREEN: "PayScreen",
});
